# Generated by Django 5.2.5 on 2025-08-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(choices=[('metric', 'metric'), ('imperial', 'imperial')], default='metric', max_length=10)),
                ('temp', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('condition', models.CharField(max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='api', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='weather.city')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['city', '-fetched_at'], name='weather_wea_city_id_2001ed_idx')],
            },
        ),
    ]
